apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
        - targetRepo  # CHANGED
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
        targetRepo:  # CHANGED
          type: string
          title: Target GitHub Repository
          description: "Select the GitHub repository where the YAML file will be published."  # CHANGED
          ui:field: RepoPicker  # CHANGED
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          cluster_name: ${{ parameters.clusterName }}
          provider_instance_size_name: ${{ parameters.clusterSize }}
          currentDate: ${{ (new Date()).toISOString().split('T')[0] }}
    - id: publish-to-github
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.targetRepo }}  # CHANGED
        branch: main
        filePath: "new_cluster_requests/${{ parameters.clusterName }}.yaml"

