apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
        - repoUrl  # CHANGED
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
        repoUrl:
          title: Repository Location
          type: string
          default: "github.com/barronandersonmongo/landing-zone-backstage-launch-pad"  # Default value
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          cluster_name: ${{ parameters.clusterName }}
          provider_instance_size_name: ${{ parameters.clusterSize }}
          currentDate: ${{ (new Date()).toISOString().split('T')[0] }}

    - id: debug-log
      name: Log Repository URL
      action: debug:log
      input:
        message: "Publishing to repository: ${{ parameters.targetRepo }}"

    - id: publish-to-github
      name: Publish to GitHub
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}  # CHANGED
        branch: main
        filePath: "new_cluster_requests/${{ parameters.clusterName }}.yaml"

