apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
        - comments
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
        comments:
          title: Request Comments
          type: string
        junk:
          title: JunkU
          type: string
  steps:

    - id: write-to-file
      name: Overwrite File Or Create New
      action: roadiehq:utils:fs:write
      input:
        path: ./new_cluster_requests/${{ parameters.clusterName }}.yaml
        content: |
          cluster_name: ${{ parameters.clusterName }}
          provider_instance_size_name: ${{ parameters.clusterSize == 'Large' ? 'M30' : parameters.clusterSize == 'Medium' ? 'M20' : 'M10' }}

    - id: publish-pr
      name: Publish PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=barronandersonmongo&repo=tfe-test
        branchName: "feature/new-cluster-${{ parameters.clusterName }}" 
        defaultBranch: main
        title: New Cluster Request for ${{ parameters.clusterName }}
        description: This PR was created by a Backstage scaffolder task

    - id: log-message
      name: Log PR URL
      action: debug:log
      input:
        message: 'BARRY BARRY BARRY - RemoteURL: ${{ steps["publish-pr"].output.remoteUrl }}'
