apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
        comments:
          title: Request Comments
          type: string
        junk:
          title: Junkc
          type: string
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/barronandersonmongo/tfe-test

    - id: create-file
      name: Create Cluster Config File
      action: roadiehq:utils:fs:write
      input:
        path: "new_cluster_requests/${{ parameters.clusterName }}.yaml"
        content: |
          cluster_name: ${{ parameters.clusterName }}
          provider_instance_size_name: ${{ parameters.clusterSize }}

    - id: publish-to-github
      name: Publish to GitHub
      action: github:repo:push
      input:
        repoUrl: "github.com?owner=barronandersonmongo&repo=tfe-test"
        defaultBranch: main
        branch: main
        branchName: main
        sourcePath: "new_cluster_requests/"
        gitCommitMessage: ${{ parameters.comments }}
        force: true
