apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
        - comments
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
        comments:
          title: Request Comments
          type: string
        junk:
          title: JunkO
          type: string
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/barronandersonmongo/tfe-test

    - id: write-to-file
      name: Overwrite File Or Create New
      action: roadiehq:utils:fs:write
      input:
        path: ./new_cluster_requests/${{ parameters.clusterName }}.yaml
        content: |
          clusterName: ${{ parameters.clusterName }}
          clusterSize: ${{ parameters.clusterSize }}

    - id: publish-pr
      name: Publish PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=tfe-test&owner=barronandersonmongo
        branchName: main
        title: Write content to main
        description: Testing

    - id: log-message
      name: Log PR URL
      action: debug:log
      input:
        message: 'RemoteURL: ${{ steps["publish-pr"].output.remoteUrl }}'
