apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
        - comments
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
        comments:
          title: Request Comments
          type: string
        junk:
          title: JunkM
          type: string
  steps:
    - id: create-file
      name: Create Cluster Config File
      action: roadiehq:utils:fs:write
      input:
        path: ./new_cluster_requests/${{ parameters.clusterName }}.yaml
        content: |
          clusterName: ${{ parameters.clusterName }}
          clusterSize: ${{ parameters.clusterSize }}

    - id: commit-changes
      name: Commit Changes
      action: github:repo:push
      input:
        repoUrl: "github.com?owner=barronandersonmongo&repo=tfe-test"
        branch: main
        defaultBranch: main
        branchName: main
        sourcePath: ./new_cluster_requests/
        gitCommitMessage: "Add cluster configuration for ${{ parameters.clusterName }}"
        force: true
