apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Asks user for cluster details and publishes a YAML configuration file to a target GitHub repository."
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - Small
            - Medium
            - Large
  steps:
    - id: generate-yaml
      name: Generate YAML Configuration
      action: write:template
      input:
        targetPath: "new_cluster_requests/${{ parameters.clusterName }}.yaml"
        content: |
          cluster_name: ${{ parameters.clusterName }}
          provider_instance_size_name: ${{ parameters.clusterSize == 'Large' ? 'M30' : parameters.clusterSize == 'Medium' ? 'M20' : 'M10' }}
          created_date: ${{ (new Date()).toISOString().split('T')[0] }}
    - id: publish-to-github
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com/barronandersonmongo/tfe-test  # Target repo
        branch: main  # Target branch
        filePath: "new_cluster_requests/${{ parameters.clusterName }}.yaml"

