apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mongodb-cluster-config
  title: "Generate MongoDB Cluster YAML"
  description: "Creates a YAML configuration file for MongoDB Atlas clusters"
spec:
  owner: gary@barry.mdbpsce.net
  type: configuration
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - clusterSize
      properties:
        clusterName:
          type: string
          title: Cluster Name
        clusterSize:
          type: string
          title: Cluster Size
          enum:
            - small
            - large
  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton  # Reference the local skeleton directory
        values:
          clusterName: ${{ parameters.clusterName }}
          clusterSize: ${{ parameters.clusterSize }}
          currentDate: ${{ (new Date()).toISOString().split('T')[0] }}
    - id: publish
      name: Publish to Local Directory
      action: publish:file
      input:
        targetPath: "./output/${{ parameters.clusterName }}-${{ (new Date()).toISOString().split('T')[0] }}.yaml"

